language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

before_install:
  - sudo apt-get update -qq

install:
  - pip install .

script:
  - python -m doctest checkimpcont.py < "/dev/null"
  - ./tests/test_contorted.sh
  - checkimpcont.py checkimpcont.py
